import type { ServerEnv } from "@dashora/shared";

export type TestServerEnv = Pick<
  ServerEnv,
  | "NODE_ENV"
  | "CORS_ORIGIN"
  | "TRUST_PROXY"
  | "COOKIE_SECURE"
  | "SESSION_TTL_MS"
  | "SESSION_RENEWAL_THRESHOLD_MS"
  | "SETUP_TOKEN_TTL_MS"
  | "LOGIN_RATE_LIMIT_MAX"
  | "LOGIN_RATE_LIMIT_WINDOW_MS"
  | "SETUP_RATE_LIMIT_MAX"
  | "SETUP_RATE_LIMIT_WINDOW_MS"
  | "AUTH_ME_RATE_LIMIT_MAX"
  | "AUTH_ME_RATE_LIMIT_WINDOW_MS"
  | "API_RATE_LIMIT_MAX"
  | "API_RATE_LIMIT_WINDOW_MS"
  | "HSTS_MAX_AGE_SECONDS"
  | "MAX_BODY_BYTES"
  | "PUBLIC_BASE_URL"
  | "PORT"
  | "PROVIDER_USER_AGENT"
  | "PROVIDER_CONNECT_TIMEOUT_MS"
  | "PROVIDER_REQUEST_TIMEOUT_MS"
  | "PROVIDER_MAX_RESPONSE_BYTES"
  | "PROVIDER_MAX_REDIRECTS"
  | "PROVIDER_RATE_LIMIT_MAX"
  | "PROVIDER_RATE_LIMIT_WINDOW_MS"
  | "PROVIDER_CIRCUIT_FAILURE_THRESHOLD"
  | "PROVIDER_CIRCUIT_OPEN_MS"
  | "PROVIDER_CACHE_TTL_SECONDS"
  | "PROVIDER_CACHE_SWR_SECONDS"
  | "SECRETS_ENCRYPTION_KEY"
  | "GITHUB_TOKEN"
  | "COINGECKO_API_KEY"
  | "FINNHUB_API_KEY"
  | "REDDIT_CLIENT_ID"
  | "REDDIT_CLIENT_SECRET"
  | "TWITCH_CLIENT_ID"
  | "TWITCH_CLIENT_SECRET"
  | "BACKUP_IMPORT_MAX_BYTES"
>;

export function createTestServerEnv(overrides: Partial<TestServerEnv> = {}): TestServerEnv {
  return {
    NODE_ENV: "test",
    CORS_ORIGIN: "http://localhost:5173",
    TRUST_PROXY: false,
    COOKIE_SECURE: false,
    SESSION_TTL_MS: 60_000,
    SESSION_RENEWAL_THRESHOLD_MS: 30_000,
    SETUP_TOKEN_TTL_MS: 60 * 60 * 1000,
    LOGIN_RATE_LIMIT_MAX: 100,
    LOGIN_RATE_LIMIT_WINDOW_MS: 60_000,
    SETUP_RATE_LIMIT_MAX: 100,
    SETUP_RATE_LIMIT_WINDOW_MS: 60_000,
    AUTH_ME_RATE_LIMIT_MAX: 100,
    AUTH_ME_RATE_LIMIT_WINDOW_MS: 60_000,
    API_RATE_LIMIT_MAX: 1_000,
    API_RATE_LIMIT_WINDOW_MS: 60_000,
    HSTS_MAX_AGE_SECONDS: 15_552_000,
    MAX_BODY_BYTES: 1_000_000,
    PORT: 3000,
    PROVIDER_USER_AGENT: "Dashora/0.1.0-test (+https://github.com/GitTheums/Dashora)",
    PROVIDER_CONNECT_TIMEOUT_MS: 2_000,
    PROVIDER_REQUEST_TIMEOUT_MS: 5_000,
    PROVIDER_MAX_RESPONSE_BYTES: 1_000_000,
    PROVIDER_MAX_REDIRECTS: 3,
    PROVIDER_RATE_LIMIT_MAX: 100,
    PROVIDER_RATE_LIMIT_WINDOW_MS: 60_000,
    PROVIDER_CIRCUIT_FAILURE_THRESHOLD: 3,
    PROVIDER_CIRCUIT_OPEN_MS: 1_000,
    PROVIDER_CACHE_TTL_SECONDS: 60,
    PROVIDER_CACHE_SWR_SECONDS: 300,
    SECRETS_ENCRYPTION_KEY: "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef",
    BACKUP_IMPORT_MAX_BYTES: 8_000_000,
    ...overrides,
  };
}
