/**
 * A small denylist of the most commonly leaked/breached passwords (publicly known, generic —
 * not sourced from any specific product). Length alone is a weak signal; rejecting these closes
 * the most common credential-stuffing / dictionary-attack targets without imposing arbitrary
 * character-composition rules (NIST 800-63B recommends denylists over forced complexity).
 */
export const COMMON_PASSWORD_DENYLIST: ReadonlySet<string> = new Set(
  [
    "123456",
    "123456789",
    "12345678",
    "12345",
    "1234567",
    "1234567890",
    "1234",
    "111111",
    "000000",
    "password",
    "password1",
    "password123",
    "passw0rd",
    "qwerty",
    "qwerty123",
    "qwertyuiop",
    "1q2w3e4r",
    "1qaz2wsx",
    "qazwsx",
    "abc123",
    "abcd1234",
    "iloveyou",
    "monkey",
    "dragon",
    "letmein",
    "trustno1",
    "sunshine",
    "master",
    "welcome",
    "welcome1",
    "shadow",
    "superman",
    "batman",
    "starwars",
    "michael",
    "jennifer",
    "jessica",
    "michelle",
    "charlie",
    "andrew",
    "joshua",
    "daniel",
    "matthew",
    "thomas",
    "robert",
    "george",
    "amanda",
    "ashley",
    "nicole",
    "chelsea",
    "taylor",
    "hunter",
    "hunter2",
    "buster",
    "soccer",
    "hockey",
    "football",
    "baseball",
    "basketball",
    "tigger",
    "harley",
    "ranger",
    "cheese",
    "pepper",
    "ginger",
    "summer",
    "winter",
    "autumn",
    "princess",
    "flower",
    "butterfly",
    "ilovegod",
    "jesus",
    "computer",
    "internet",
    "startrek",
    "pokemon",
    "minecraft",
    "fortnite",
    "freedom",
    "whatever",
    "biteme",
    "access",
    "admin",
    "administrator",
    "root",
    "toor",
    "letmein1",
    "login",
    "loginpassword",
    "changeme",
    "changeme123",
    "temppassword",
    "temp1234",
    "guest",
    "guest123",
    "test123",
    "testing",
    "sample",
    "default",
    "passwordpassword",
    "asdfasdf",
    "asdfghjkl",
    "zxcvbnm",
    "zxcvbn",
    "qweasdzxc",
    "121212",
    "123123",
    "112233",
    "131313",
    "159753",
    "654321",
    "696969",
    "777777",
    "888888",
    "999999",
    "11111111",
    "22222222",
    "aaaaaaaa",
    "aaaaaa",
    "1111111",
    "7777777",
    "987654321",
    "0123456789",
    "trustno1234",
    "letmeinplease",
    "iamgroot",
    "correcthorsebatterystaple",
    "passw0rd1",
    "p@ssw0rd",
    "p@ssword",
    "myspace1",
    "blahblah",
    "whatever1",
    "dragon123",
    "monkey123",
    "mustang",
    "yankees",
    "cowboys",
    "dallas",
    "austin",
    "chicago",
    "london",
    "newyork",
    "california",
    "florida",
    "texas",
    "america",
    "liverpool",
    "arsenal",
    "chelsea1",
    "manchester",
    "compaq",
    "pussycat",
    "iloveyou1",
    "iloveyou2",
    "loveyou",
    "loveme",
    "letmeout",
    "opensesame",
    "sesame",
    "dashboard",
    "dashboard1",
    "operator",
    "operator1",
    "supersecret",
    "secretpassword",
  ].map((entry) => entry.toLowerCase()),
);

export function isCommonPassword(password: string): boolean {
  return COMMON_PASSWORD_DENYLIST.has(password.trim().toLowerCase());
}

/**
 * Rejects passwords that trivially embed the account's own email local-part (e.g. email
 * `alice@example.com` choosing password `alice12345678`). Only checks the start/end of the
 * password (not a raw substring search) so ordinary words that happen to contain a common local
 * part — e.g. "another" containing "other" — are not flagged. Skips very short local-parts to
 * avoid false positives.
 */
export function passwordContainsEmailLocalPart(password: string, email: string): boolean {
  const localPart = email.split("@")[0]?.trim().toLowerCase() ?? "";
  if (localPart.length < 4) {
    return false;
  }
  const normalizedPassword = password.trim().toLowerCase();
  return (
    normalizedPassword === localPart ||
    normalizedPassword.startsWith(localPart) ||
    normalizedPassword.endsWith(localPart)
  );
}
